[package]
name = "dioxus-rust-i18n-macro"
description = "Proc macros for dioxus-rust-i18n"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
rust-i18n.workspace = true
syn = { workspace = true, features = ["full"] }
