#![doc = include_str!("../README.md")]

use std::env;
use std::path::PathBuf;

use proc_macro::TokenStream;
use quote::quote;
use syn::parse::{Parse, ParseStream};
use syn::punctuated::Punctuated;
use syn::{Expr, ExprLit, Lit, LitStr, Result, Token, parse_macro_input};

/// Wraps the [`rust_i18n::i18n!`] macro and additionally generates
/// Dioxus bridge helpers.
///
/// The generated items include a zero-argument
/// `use_init_i18n` function in the consumer crate, plus
/// hidden bridge symbols used to construct a Dioxus-aware runtime from the
/// upstream `rust-i18n` backend.
#[proc_macro]
pub fn i18n(input: TokenStream) -> TokenStream {
    let raw_input = proc_macro2::TokenStream::from(input.clone());
    let args = parse_macro_input!(input as I18nArgs);

    expand_i18n(raw_input, args).into()
}

struct I18nArgs {
    locales_path: Option<LitStr>,
}

impl Parse for I18nArgs {
    fn parse(input: ParseStream<'_>) -> Result<Self> {
        let args = Punctuated::<Expr, Token![,]>::parse_terminated(input)?;
        let locales_path = match args.first() {
            Some(Expr::Lit(ExprLit {
                lit: Lit::Str(path),
                ..
            })) => Some(path.clone()),
            _ => None,
        };

        Ok(Self { locales_path })
    }
}

fn expand_i18n(raw_input: proc_macro2::TokenStream, args: I18nArgs) -> proc_macro2::TokenStream {
    if let Some(locales_path) = &args.locales_path {
        let manifest_dir = match env::var("CARGO_MANIFEST_DIR") {
            Ok(value) => value,
            Err(_) => {
                return syn::Error::new(
                    locales_path.span(),
                    "CARGO_MANIFEST_DIR is not available during macro expansion",
                )
                .to_compile_error();
            }
        };

        let resolved_path = PathBuf::from(manifest_dir).join(locales_path.value());
        if !resolved_path.exists() {
            return syn::Error::new(
                locales_path.span(),
                format!("locale path `{}` does not exist", resolved_path.display()),
            )
            .to_compile_error();
        }
    }

    quote! {
        ::rust_i18n::i18n!(#raw_input);

        #[doc(hidden)]
        pub mod __dioxus_rust_i18n_generated {
            pub struct GeneratedBackend;

            impl ::rust_i18n::Backend for GeneratedBackend {
                fn available_locales(&self) -> ::std::vec::Vec<::std::borrow::Cow<'_, str>> {
                    super::_RUST_I18N_BACKEND.available_locales()
                }

                fn translate(&self, locale: &str, key: &str) -> ::std::option::Option<::std::borrow::Cow<'_, str>> {
                    super::_rust_i18n_try_translate(locale, key)
                }

                fn messages_for_locale(
                    &self,
                    locale: &str,
                ) -> ::std::option::Option<
                    ::std::vec::Vec<(
                        ::std::borrow::Cow<'_, str>,
                        ::std::borrow::Cow<'_, str>,
                    )>,
                > {
                    super::_RUST_I18N_BACKEND.messages_for_locale(locale)
                }
            }

            pub fn compiled_runtime() -> ::dioxus_rust_i18n::I18nRuntime {
                let initial_locale = super::_RUST_I18N_FALLBACK_LOCALE
                    .and_then(|locales| locales.first().copied())
                    .unwrap_or("en");

                ::dioxus_rust_i18n::I18nRuntime::from_backend(
                    initial_locale,
                    GeneratedBackend,
                )
            }
        }

        /// Initializes the generated `rust-i18n` catalog for the current Dioxus tree.
        ///
        /// This function is generated by `dioxus_rust_i18n::i18n!(...)` in the consumer crate.
        pub fn use_init_i18n() -> ::dioxus_rust_i18n::I18nSession {
            ::dioxus_rust_i18n::use_init_i18n_from(|| {
                __dioxus_rust_i18n_generated::compiled_runtime()
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse_args(input: &str) -> I18nArgs {
        syn::parse_str(input).expect("test input should parse")
    }

    #[test]
    fn parse_reads_leading_string_literal_as_locales_path() {
        let args = parse_args("\"locales\", fallback = [\"en\"]");

        assert_eq!(args.locales_path.unwrap().value(), "locales");
    }

    #[test]
    fn parse_ignores_non_literal_head_for_locales_path() {
        let args = parse_args("shared_locales(), fallback = [\"en\"]");

        assert!(args.locales_path.is_none());
    }
}
